# Generated by Django 5.0.4 on 2024-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('e', 'No Label'), ('p', 'new'), ('d', 'best seller')], max_length=1),
        ),
    ]
